CREATE TABLE CATALOG (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  TITLE VARCHAR(100),
  ARTIST VARCHAR(100),
  COUNTRY VARCHAR(100),
  COMPANY VARCHAR(100),
  PRICE VARCHAR(100),
  YEAR VARCHAR(100)
);

CREATE TABLE HEADERS (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT, 
  CD_ID BIGINT(20),
  HEADERS VARCHAR(2000)
);